//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplrSales.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SimplrSalesEdmxEntities : DbContext
    {
        public SimplrSalesEdmxEntities()
            : base("name=SimplrSalesEdmxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SalesOfficeProc_Result> SalesOfficeProc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SalesOfficeProc_Result>("SalesOfficeProc");
        }
    
        public virtual ObjectResult<ExportQueryConfigProc_Result> ExportQueryConfigProc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ExportQueryConfigProc_Result>("ExportQueryConfigProc");
        }
    }
}
